name: Run BOT-JS1.6.0

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  run-bot:
    runs-on: windows-latest
    timeout-minutes: 360
    permissions:
      contents: write
    env:
      TZ: Asia/Ho_Chi_Minh

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies & replace nsfwjs
        run: |
          npm install
          Remove-Item -Recurse -Force node_modules\nsfwjs
          Copy-Item -Recurse -Force nsfwjs.u node_modules\nsfwjs
        shell: powershell

      - name: Run bot
        run: node src/index.js
        shell: powershell
