name: Run BOT-JS1.6.0

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  run-bot:
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    permissions:
      contents: write
    env:
      TZ: Asia/Ho_Chi_Minh

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Clone BOT-JS1.6.0
        run: git clone https://github.com/depchaiaiyeu/BOT-JS1.6.0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies & replace nsfwjs
        run: |
          cd BOT-JS1.6.0
          npm install
          rm -rf node_modules/nsfwjs
          cp -r nsfwjs.u node_modules/nsfwjs

      - name: Optimize network for low latency
        run: |
          sudo modprobe tcp_bbr
          sudo sysctl -w net.ipv4.tcp_fastopen=3
          sudo sysctl -w net.core.rmem_max=16777216
          sudo sysctl -w net.core.wmem_max=16777216
          sudo sysctl -w net.ipv4.tcp_rmem="4096 87380 16777216"
          sudo sysctl -w net.ipv4.tcp_wmem="4096 65536 16777216"
          sudo sysctl -w net.core.netdev_max_backlog=250000
          sudo sysctl -w net.ipv4.tcp_congestion_control=bbr
          sudo sysctl -w net.ipv4.tcp_low_latency=1
          sudo iptables -t mangle -A OUTPUT -p udp --dport 80 -j TOS --set-tos 0x10
          sudo iptables -t mangle -A OUTPUT -p udp --dport 443 -j TOS --set-tos 0x10

      - name: Run bot
        run: |
          cd BOT-JS1.6.0
          node src/index.js

      - name: Commit and push changes
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: |
          cd BOT-JS1.6.0
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git reset package-lock.json 2>/dev/null || true
          git reset node_modules 2>/dev/null || true
          if ! git diff --staged --quiet; then
            git commit -m "Auto commit changes from workflow"
            git push https://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@github.com/depchaiaiyeu/BOT-JS1.6.0.git
          fi
